"""added is login status of the user

Revision ID: bd1527cf68fe
Revises: 9411351c4284
Create Date: 2026-05-18 21:37:45.756349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1527cf68fe'
down_revision: Union[str, Sequence[str], None] = '9411351c4284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_users', sa.Column('is_login', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_users', 'is_login')
    # ### end Alembic commands ###
